export const categories = [
  {
    title: "Furniture",
    value: "furniture",
    image: "productImages/product13.png",
  },
  {
    title: "Electronics",
    value: "electronics",
    image: "productImages/product3.png",
  },
  // { title: "Chairs", value: "chairs", image: "productImages/product6.png" },
  // {
  //   title: "Headphones",
  //   value: "headphones",
  //   image: "productImages/product4.png",
  // },
  {
    title: "Accessories",
    value: "accessories",
    image: "productImages/product2.png",
  },
];

export const productExamples = [
  {
    name: "Bagpack padded black Model 10",
    image: "productImages/product1.png",
    code: "Y1234i",
    price: 299.99,
    colors: [{ colorName: "black", value: "#000000" }],
    views: 50,
    sales: 15,
    categories: ["bag", "accessories"],
    rating: 4.5,
    numReviews: 12,
    brands: ["Wisdom Pack", "Bag Lovers"],
    discount: 15,
    desc: "a very beautiful and comfortable bag, which will make your life easier with it's ease of use and planty of storage.",
    countInStock: 50,
  },
  {
    name: "Catevilever Watch Model 12",
    image: "productImages/product2.png",
    code: "Y55434i",
    price: 2449.99,
    colors: [{ colorName: "black", value: "#000000" }],
    views: 89,
    sales: 55,
    categories: ["accessories", "watch", "electronics"],
    rating: 5,
    numReviews: 22,
    brands: ["Catevilever"],
    desc: "a very beautiful and comfortable watch, which will make your life better by showing you that time is valueable.",
    countInStock: 40,
  },
  {
    name: "Stromisier EOS 80D DSLR Camera",
    image: "productImages/product3.png",
    code: "Y1fyf4i",
    price: 1554.99,
    colors: [{ colorName: "black", value: "#000000" }],
    views: 52,
    sales: 45,
    categories: ["electronics", "camera"],
    rating: 4.5,
    numReviews: 23,
    brands: ["Stromisier"],
    desc: "a very beautiful camera, which will cature the greatest moments of your life and make you feel like they're happening all over again",
    countInStock: 70,
  },
  {
    name: "Stromisier Wireless Bluetooth Headphones",
    image: "productImages/product4.png",
    code: "U1grf5i",
    price: 89.99,
    colors: [
      { colorName: "purple", value: "#800080" },
      { colorName: "pink", value: "#953553" },
    ],
    views: 59,
    sales: 20,
    categories: ["electronics", "headphones"],
    rating: 3,
    numReviews: 10,
    brands: ["Coaster Blue", "Yellow Furniture"],
    discount: 45,
    desc: "very beautiful waterproof and wiresless headphones with great sound quality. Very comfortable ato wear all day long.",
    countInStock: 30,
  },
  {
    name: "Coaster Furniture & Green DIY Furniture Chair",
    image: "productImages/product5.png",
    code: "Y5674i",
    price: 3199.99,
    colors: [{ colorName: "blue", value: "#82aaea" }],
    views: 28,
    sales: 15,
    categories: ["furniture", "chair"],
    rating: 5,
    numReviews: 10,
    brands: ["Coaster Furniture", "Green DIY Furniture"],
    discount: 25,
    desc: "a very beautiful and comfortable chair with removable cushions and incredible quality.",
    featured: true,
    countInStock: 65,
  },
  {
    name: "Coaster Furniture Chair Model 3",
    image: "productImages/product6.png",
    code: "Y13434i",
    price: 499.99,
    colors: [
      { colorName: "beige", value: "#ded8c5" },
      { colorName: "brown", value: "#6d4622" },
    ],
    views: 50,
    sales: 10,
    categories: ["furniture", "chair"],
    rating: 3,
    numReviews: 4,
    brands: ["Coaster Furniture"],
    desc: "a very beautiful and comfortable chair. Incredible quality. Not just a chair, but a stunning art piece.",
    featured: true,
    countInStock: 20,
  },
  {
    name: "Yellow Furniture Chair Model 5",
    image: "productImages/product7.png",
    code: "U1yuf4i",
    price: 399.99,
    colors: [
      { colorName: "white", value: "#a89d8b" },
      { colorName: "beige", value: "#d49c67" },
    ],
    views: 100,
    sales: 45,
    categories: ["furniture", "chair"],
    rating: 3.5,
    numReviews: 5,
    brands: ["Yellow Furniture"],
    desc: "a very beautiful and comfortable chair. Incredible quality. Not just a chair, but a stunning art piece.",
    featured: true,
    countInStock: 32,
  },
  {
    name: "Coaster Blue Chair Model 5F",
    image: "productImages/product8.png",
    code: "U1fdf4i",
    price: 425.99,
    colors: [{ colorName: "gray", value: "#aeada9" }],
    views: 110,
    sales: 78,
    categories: ["furniture", "chair"],
    rating: 5,
    numReviews: 8,
    brands: ["Coaster Blue"],
    desc: "a very beautiful and comfortable chair. Incredible quality. Not just a chair, but a stunning art piece.",
    countInStock: 22,
  },
  {
    name: "Yellow Chair Model 1C by Coaster Blue",
    image: "productImages/product9.png",
    code: "U1fdf4i",
    price: 425.99,
    colors: [
      { colorName: "yellow", value: "#ecaa01" },
      { colorName: "beige", value: "#75513e" },
    ],
    views: 110,
    sales: 78,
    categories: ["furniture", "chair"],
    rating: 5,
    numReviews: 12,
    brands: ["Coaster Blue"],
    desc: "a very beautiful and comfortable chair. Incredible quality. Not just a chair, but a stunning art piece.",
    featured: true,
    countInStock: 45,
  },
  {
    name: "Gray Chair Model 2B by Yellow Furniture",
    image: "productImages/product10.png",
    code: "Z1fdf4i",
    price: 355.99,
    colors: [{ colorName: "gray", value: "#ddd9d6" }],
    views: 170,
    sales: 100,
    categories: ["furniture", "chair"],
    rating: 3,
    numReviews: 12,
    brands: ["Yellow Furniture"],
    desc: "a very beautiful and comfortable chair. Incredible quality. Not just a chair, but a stunning art piece.",
    countInStock: 43,
  },
  {
    name: "Lamp Model 3F by Yellow Furniture",
    image: "productImages/product11.png",
    code: "Z9fdf4i",
    price: 56.99,
    colors: [
      { colorName: "black", value: "#000000" },
      { colorName: "gold", value: "#e79b32" },
    ],
    views: 89,
    sales: 45,
    categories: ["furniture", "lamp"],
    rating: 3,
    numReviews: 3,
    brands: ["Yellow Furniture"],
    desc: "a very beautiful lamp. Incredible quality. Not just a lamp, but a stunning art piece that will leave everyone speechless.",
    countInStock: 21,
  },
  {
    name: "Chair Model 4G by Yellow Furniture",
    image: "productImages/product12.png",
    code: "Z8fdg4i",
    price: 799.99,
    colors: [
      { colorName: "black", value: "#000000" },
      { colorName: "red", value: "#690d0e" },
    ],
    views: 150,
    sales: 110,
    categories: ["furniture", "chair"],
    rating: 3,
    numReviews: 13,
    brands: ["Yellow Furniture"],
    desc: "a very beautiful and comfortable chair. Incredible quality. Not just a chair, but a stunning art piece.",
    featured: true,
    countInStock: 30,
  },
];
